LOAD DATA LOCAL INFILE "C:\\Users\\cfee\\git\\tsvtocsv\\nameBasic.csv"
INTO TABLE mydb.person
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\'
LINES TERMINATED BY '\r\n' STARTING BY ''
IGNORE 0 LINES;

