-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 16:14:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb2` DEFAULT CHARACTER SET utf8 ;
USE `mydb2` ;

-- -----------------------------------------------------
-- Table `mydb2`.`Cast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Cast` (
  `idCast` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCast`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Title` (
  `idTitle` INT NOT NULL,
  `type` VARCHAR(15) NULL,
  `primaryTitle` VARCHAR(45) NULL,
  `originalTitle` VARCHAR(45) NULL,
  `isAdult` TINYINT NULL,
  `startYear` INT NULL,
  `endYear` INT NULL,
  `runtime` INT NULL,
  `Cast_idCast` INT NOT NULL,
  PRIMARY KEY (`idTitle`),
  INDEX `fk_Title_Cast1_idx` (`Cast_idCast` ASC),
  CONSTRAINT `fk_Title_Cast1`
    FOREIGN KEY (`Cast_idCast`)
    REFERENCES `mydb2`.`Cast` (`idCast`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Genres` (
  `idGenre` INT NOT NULL,
  `genre` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Episode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Episode` (
  `Title_idTitle` INT NOT NULL,
  `idParent` INT NOT NULL,
  `season` SMALLINT(5) NULL,
  `number` SMALLINT(5) NULL,
  PRIMARY KEY (`Title_idTitle`, `idParent`),
  INDEX `fk_Episode_Title1_idx` (`Title_idTitle` ASC),
  CONSTRAINT `fk_Episode_Title1`
    FOREIGN KEY (`Title_idTitle`)
    REFERENCES `mydb2`.`Title` (`idTitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Rating` (
  `Title_idTitle` INT NOT NULL,
  `averageRating` FLOAT NULL,
  `numVotes` INT NULL,
  PRIMARY KEY (`Title_idTitle`),
  CONSTRAINT `fk_Rating_Title1`
    FOREIGN KEY (`Title_idTitle`)
    REFERENCES `mydb2`.`Title` (`idTitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Metadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Metadata` (
  `Title_idTitle` INT NOT NULL,
  `color` VARCHAR(10) NULL,
  `directorFBLikes` INT NULL,
  `gross` INT NULL,
  `title` VARCHAR(100) NULL,
  `castTotalFBLikes` INT NULL,
  `movieIMDBLink` VARCHAR(100) NULL,
  `language` VARCHAR(20) NULL,
  `country` VARCHAR(20) NULL,
  `contentRating` VARCHAR(10) NULL,
  `budget` INT NULL,
  `imdbScore` FLOAT NULL,
  `aspectRatio` FLOAT NULL,
  `movieFBLikes` INT NULL,
  PRIMARY KEY (`Title_idTitle`),
  CONSTRAINT `fk_MetaData_Title1`
    FOREIGN KEY (`Title_idTitle`)
    REFERENCES `mydb2`.`Title` (`idTitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`ExtraMetaData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`ExtraMetaData` (
  `Metadata_Title_idTitle` INT NOT NULL,
  `rank` INT NULL,
  `metascore` INT NULL,
  `revenue` FLOAT NULL,
  `votes` INT NULL,
  `description` VARCHAR(250) NULL,
  PRIMARY KEY (`Metadata_Title_idTitle`),
  CONSTRAINT `fk_ExtraMetaData_MetaData1`
    FOREIGN KEY (`Metadata_Title_idTitle`)
    REFERENCES `mydb2`.`Metadata` (`Title_idTitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Person` (
  `idPerson` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `birthYear` INT NULL,
  `deathYear` INT NULL,
  `FBLikes` INT NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Profession` (
  `idProfession` INT NOT NULL,
  `profession` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfession`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`PersonProfessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`PersonProfessions` (
  `idPerson` INT NOT NULL,
  `idProfession` INT NOT NULL,
  PRIMARY KEY (`idPerson`, `idProfession`),
  INDEX `fk_Professions_has_Person_Person1_idx` (`idPerson` ASC),
  INDEX `fk_Professions_has_Person_Professions1_idx` (`idProfession` ASC),
  CONSTRAINT `fk_Professions_has_Person_Professions1`
    FOREIGN KEY (`idProfession`)
    REFERENCES `mydb2`.`Profession` (`idProfession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professions_has_Person_Person1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb2`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`TitleGenres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`TitleGenres` (
  `Title_idTitle` INT NOT NULL,
  `Genres_idGenre` INT NOT NULL,
  PRIMARY KEY (`Title_idTitle`, `Genres_idGenre`),
  INDEX `fk_Genres_has_Title_Title1_idx` (`Title_idTitle` ASC),
  INDEX `fk_Genres_has_Title_Genres1_idx` (`Genres_idGenre` ASC),
  CONSTRAINT `fk_Genres_has_Title_Genres1`
    FOREIGN KEY (`Genres_idGenre`)
    REFERENCES `mydb2`.`Genres` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Genres_has_Title_Title1`
    FOREIGN KEY (`Title_idTitle`)
    REFERENCES `mydb2`.`Title` (`idTitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Cast_has_Person_with_Profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Cast_has_Person_with_Profession` (
  `Cast_idCast` INT NOT NULL,
  `Person_idPerson` INT NOT NULL,
  `Professions_idProfession` INT NOT NULL,
  PRIMARY KEY (`Cast_idCast`, `Person_idPerson`, `Professions_idProfession`),
  INDEX `fk_Cast_has_Person_Person1_idx` (`Person_idPerson` ASC),
  INDEX `fk_Cast_has_Person_Cast1_idx` (`Cast_idCast` ASC),
  INDEX `fk_Cast_has_Person_with_Profession_Professions1_idx` (`Professions_idProfession` ASC),
  CONSTRAINT `fk_Cast_has_Person_Cast1`
    FOREIGN KEY (`Cast_idCast`)
    REFERENCES `mydb2`.`Cast` (`idCast`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cast_has_Person_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb2`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cast_has_Person_with_Profession_Professions1`
    FOREIGN KEY (`Professions_idProfession`)
    REFERENCES `mydb2`.`Profession` (`idProfession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Keyword` (
  `idKeyword` INT NOT NULL,
  `keyword` VARCHAR(45) NULL,
  PRIMARY KEY (`idKeyword`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Metadata_Keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Metadata_Keywords` (
  `MetaData_Title_idTitle` INT NOT NULL,
  `Keyword_idKeyword` INT NOT NULL,
  PRIMARY KEY (`MetaData_Title_idTitle`, `Keyword_idKeyword`),
  INDEX `fk_MetaData_has_Keyword_Keyword1_idx` (`Keyword_idKeyword` ASC),
  INDEX `fk_MetaData_has_Keyword_MetaData1_idx` (`MetaData_Title_idTitle` ASC),
  CONSTRAINT `fk_MetaData_has_Keyword_MetaData1`
    FOREIGN KEY (`MetaData_Title_idTitle`)
    REFERENCES `mydb2`.`Metadata` (`Title_idTitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MetaData_has_Keyword_Keyword1`
    FOREIGN KEY (`Keyword_idKeyword`)
    REFERENCES `mydb2`.`Keyword` (`idKeyword`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

